### ISSUE TITLE
Read BigFiles with GriddedSpectra

### ISSUE THREAD

**Issue by andreufont** [sbird/fake_spectra#1]
Keir has some code to measure P3D from simulated spectra, but it runs on HDF5 files only. In order to use it on BigFiles, I believe I just need to modify the constructor of GriddedSpectra to use AbstractSnapshotFactory like RandSpectra does. I will work on it and submit a pull request.

**Comment by sbird** [comment]
Thanks - that's right, I missed GriddedSpectra when doing the conversion. I'll let you work on it so you get to know the code better, but let me know if you want me to do it instead.

**Comment by sbird** [comment]
Fixed with pull 1
