### ISSUE TITLE
Output positions in get_cofm

### ISSUE THREAD

**Issue by jgivans** [sbird/fake_spectra#30]
Within the Spectra class there is a function named `get_cofm` which is supposed to "find a bunch more sightlines" and give their positions as an [n, 3] shape array. My understanding is that each sightline has a unique x,y position and extends across the length of my box along the z axis. How then am I getting a unique 3D position for each skewer when I print `get_cofm`? Shouldn't 3D positions only apply to individual pixels along a skewer and not the full skewer itself?

**Comment by sbird** [comment]
The sightline positions are given as a 3D matrix. There is also an axis vector, which gives the direction of the sightline. The entry in the sightline position corresponding to the axis vector is ignored. This allows you to, eg, have sightlines 1-10 be across the length of the box along the x axis, 11-20 along the y axis and 21-30 along the z axis.
