### ISSUE TITLE
linux/limits.h

### ISSUE THREAD

**Issue by mahdiqezlou** [sbird/fake_spectra#34]
Hello

```
/usr/include/bits/local_lim.h:38:26: fatal error: linux/limits.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
```
I am getting this error on `Memex`. Does it mean something has gone bad on `memex` recently ?
I get this after attempting to `build` the package

**Comment by sbird** [comment]
Sounds like the compilation environment is messed up: limits comes from the C++ compiler.
