### ISSUE TITLE
plot_spectra crashes in constructor (label not existing)

### ISSUE THREAD

**Issue by andreufont** [sbird/fake_spectra#39]
After several months without using it myself, I tried to use fake_spectra in a new computer, and I was trying to get some simple tests. I followed the README file to try to get a plot of a spectrum, using PlottingSpectra, but the code crashes right after entering the constructor. It complains about this line:
 https://github.com/sbird/fake_spectra/blob/2b64becc4a28748cc052049b4271b72b4cd5f68e/fake_spectra/plot_spectra.py#L20

We have not set "label" yet.

I'm guessing not many people use this class?

**Comment by mahdiqezlou** [comment]
Hello
I have used this before. Yes, label should not be an optional argument, we have to pass something to it.

**Comment by andreufont** [comment]
Thanks for the quick response! It would be great if you could also update the README file, currently it does not provide a label for the plot.

**Comment by mahdiqezlou** [comment]
Of course! Just sent a pull request to Simeon.

**Comment by sbird** [comment]
Fixed now, thanks @mahdiqezlou
