### ISSUE TITLE
namespace contamination

### ISSUE THREAD

**Issue by rainwoodman** [sbird/fake_spectra#4]
By glancing at setup.py, it appears that fake_spectra installs a horde of toplevel python packages to the system.

While this gets the work done, introducing too many symbols to the global python package namespace is probably not a good idea. 

Changing this behavior will probably break a lot of downstream analysis scripts; but the fix could be as easy as changing a few imports.

**Comment by sbird** [comment]
This will not break downstram analysis scripts too much (as I don't use setup.py locally) but I don't really know how distutils works. Do you have a suggested fix?

**Comment by rainwoodman** [comment]
Let me add a demo PR.

**Comment by sbird** [comment]
Thanks

**Comment by rainwoodman** [comment]
Closed by #5
