### ISSUE TITLE
Consider modifying fake_spectra to work in non-flat cosmologies

### ISSUE THREAD

**Issue by andreufont** [sbird/fake_spectra#57]
Hi @sbird - have you considered modifying fake_spectra to work with non-flat cosmologies? Assuming that MP-Gadget already works with non-flat cosmologies (it does, right?), it would allow one to simulate Lya P1D for open / curved universes, what would be pretty cool. I believe it shouldn't be much work, we would just need to modify the computation of H(z) that is hard-coded in several places now, and ignores curvature. 

By the way, currently H(z) also ignores radiation, what makes it disagree at the 0.1% level or so with CAMB, and I always end up with a slightly wrong number of pixels (in my code I set the pixel width in Mpc, so I need H(z) to convert that into velocity units to feed to fake_spectra). This is a small effect, though, so probably not worth modifying the code.

**Comment by andreufont** [comment]
@Chris-Pedersen , pinging you here since you might want to follow the discussion as well.

**Comment by sbird** [comment]
Those would both be good ideas: there is nothing preventing them that I can see, just never got around to doing it. I would certainly accept a PR! MP-Gadget should be fine with closed/open cosmologies, I have even run some boxes like that.

**Comment by andreufont** [comment]
I've looked a bit at the code, and I think I have a possible solution in mind. 

First of all, however, let me make sure I understand the overall structure of the code. The script "main.cpp" is only used when using the c++ interface, and it is not used at all when running from python. Correct? Assuming this is the case, then I think we could first focus on a solution that works for the python version (although it would be trivial to add the option also for the c++ interface).

The easiest solution (by far, I think), would be to allow the user to provide a value of H(z) that should be used to compute velfac (relation between comoving coordinates and velocity units). Something like --use_external_Hz that would not be set by default, or set to None, or whatever. If the user provides this, it would use this value, otherwise it would assume a simple flat LCDM model and compute H(z) from the cosmological parameters that were read from the simulation files. 

Alternatively, one could try to read all relevant cosmological parameters (curvature, w_0, w_a, neutrino species, etc.) and self-consistently figure out the value of H(z), but there will always be more complex models that people want to try, and we might end up re-writting CAMB inside fake_spectra :-)

If you agree with the idea of simply providing the desired value of Hz by hand as an optional argument in the constructor of spectra.py, I will start a PR (maybe tomorrow, maybe once I'm back from vacations).

**Comment by sbird** [comment]
>The script "main.cpp" is only used when using the c++ interface, and it is not used at all when running from python. Correct? >Assuming this is the case, then I think we could first focus on a solution that works for the python version (although it would >be trivial to add the option also for the c++ interface).

Yes, that's right. I think it's fine to ignore the C++ version since as far as I know it has zero users :) 

> The easiest solution (by far, I think), would be to allow the user to provide a value of H(z) that should be used to compute velfac (relation between comoving coordinates and velocity units). Something like --use_external_Hz that would not be set by default, or set to None, or whatever. If the user provides this, it would use this value, otherwise it would assume a simple flat LCDM model and compute H(z) from the cosmological parameters that were read from the simulation files.

That sounds a very good idea to me!

> Alternatively, one could try to read all relevant cosmological parameters (curvature, w_0, w_a, neutrino species, etc.) and self-consistently figure out the value of H(z), but there will always be more complex models that people want to try, and we might end up re-writting CAMB inside fake_spectra :-)

This is true! We should probably avoid that. 

> If you agree with the idea of simply providing the desired value of Hz by hand as an optional argument in the constructor of spectra.py, I will start a PR (maybe tomorrow, maybe once I'm back from vacations).

Sounds good. I'll be on vacation too next week so might be a little slow to reply.

**Comment by sbird** [comment]
Fixed by #59
