### ISSUE TITLE
clarify the difference between load_snapshot and reload_file

### ISSUE THREAD

**Issue by andreufont** [sbird/fake_spectra#58]
You can construct an instance of the class Spectra with an optional argument (reload_file=True) that will make sure that you re-compute the spectra from the simulation snapshot, even if the spectra file is present. If that option is set to false, it will try to read the pre-computed spectra file. 

However, the Spectra class has another optional argument (load_snapshot=True), and I'm not sure what this is used for. If set to true (the default), it will try to set an Snapshot instance. If it can not set that instance, it will silently ignore it and continue. If set to false, it will not try to find that snapshot, and continue. So what is the point if this second option?

**Comment by sbird** [comment]
Fair point :) I'll remove the load_snapshot option: I think it once did something more useful.
