### ISSUE TITLE
conda packaging.

### ISSUE THREAD

**Issue by rainwoodman** [sbird/fake_spectra#9]
I am thinking of adding a binary conda package on the bccp channel .. Depending how easy you want people to access this.

How is your code release cycle like? Is it still more preferred to get from git or is the code relatively stable?

**Comment by rainwoodman** [comment]
The version number on PyPI and the tar file is mismatched, one says 1.1b and the other says 1.1.

**Comment by sbird** [comment]
At the moment the code is stable (I'm not working on any papers from it). If I do more work on it I will make a new branch. I would be very happy for there to be a binary conda package.

For the versions I am using a scheme where each new 'release' is 1.X and each new build gets a different letter: is this a problem? I can make both 1.1.1 if you need me to.

**Comment by rainwoodman** [comment]
You can make both 1.1b -- as long as they are consistent we can reuse the automated system for packaging.

**Comment by sbird** [comment]
That would be great. I always screw up the manual submission thing.

**Comment by rainwoodman** [comment]
You can add a travis script to make it automatically update to pypi when you tag a release. But keeping track the consistence between tag and the version in the file is also tricky.

**Comment by rainwoodman** [comment]
https://github.com/bccp/abopt/blob/master/check_tag.sh

**Comment by sbird** [comment]
Neat - can you point me at the travis script?

**Comment by rainwoodman** [comment]
https://github.com/bccp/abopt/blob/master/.travis.yml#L28

You'll need to encrypt your password with the travis command line tool.

**Comment by sbird** [comment]
Auto-deployment implemented and 1.2.0 deployed. Thanks!

**Comment by rainwoodman** [comment]
I still have difficulty compiling the package against GLIBC 2.12 API. Looks likes you have a lot of compiler workarounds -- why redefining cexp to exp?

**Comment by sbird** [comment]
Faddeeva is lib code that I copied unmodified: I guess it has a lot of compatibility hacks. Feel free to pull them out if it helps.

**Comment by rainwoodman** [comment]
https://en.wikipedia.org/wiki/Faddeeva_function ? Do you use the integral form?

**Comment by sbird** [comment]
Yes the integral representation. From this package: http://ab-initio.mit.edu/Faddeeva

**Comment by rainwoodman** [comment]
We'll wait a bit till the new cross compilation system of anaconda works smoothly (a few weeks) Then there is no need to pin down the API. We'll just cross-compile this to a centos 6.x system.

**Comment by rainwoodman** [comment]
Done. conda install -c bccp fake_spectra.
